databases:
  - name: roulette-game
    databaseName: roulette-game
    user: roulette-game

services:
  - type: web
    name: roulette-game
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: roulette-game
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false